### ISSUE TITLE
deploy.sh SUBSCRIPTION_ID

### ISSUE THREAD

**Issue by torrilhon** [microsoft/AzureClusterlessHPC.jl#11]
Hi,

nice work! My group is exploring azure/AWS for scientific computing. 

Following the installation guide for AzureClusterlessHPC on a fresh Ubuntu 18.04 instance the deploy-script for creating azure batch and storage accounts fails with the error "invalid scope". 

As far as I could check the command 
`az account show --query subscription --output tsv`
in line 36 gives nothing. To obtain the subscription id the command 
`az account show --query id --output tsv`
must be used.

Can you comment?

**Comment by torrilhon** [comment]
I am not sure, if anyone is actually reading this...

**Comment by philippwitte** [comment]
Hi Manuel,

Sorry I missed this comment earlier. I updated the script and noticed there was also another mistake. I need to query the subscription id and tenant id separately. It should work now, but please let me know in case it still doesn't work. I'll close this for now.

Thanks!
-Philipp
